# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=production
#     depends_on:
#       - rabbitmq

#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - '5672:5672'
#       - '15672:15672'

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
